### ISSUE TITLE
Unexpected merge exception

### ISSUE THREAD

**Issue by Gabriella439** [ekmett/propagators#4]
Here is the exception I encountered:

```
>>> forwards (\x -> x ^ 2 + 4) 1
*** Exception: merge: 1 /= 0
```

I'm not sure whether this is an actual error in the library or the expected outcome, because I know that squaring is not a cleanly bidirectional operation, but I thought I should report this just in case.

**Comment by ekmett** [comment]
`(^)` is pretty badly behaved. This becomes `\x -> x*x+4`, and the system isn't smart enough to run (*) backwards when the arguments are related -- but it should run _forwards_ just fine. Hrmm.

**Comment by ekmett** [comment]
It works as expected for `Rational` and `Double`

``` haskell
>>> forwards (\x -> x ^ 2 + 4) (1 :: Rational)
Just (5 % 1)

>>> forwards (\x -> x ^ 2 + 4) (1 :: Double)
Just 5.0
```

**Comment by ekmett** [comment]
Found it.

**Comment by Gabriella439** [comment]
Awesome.  Thanks! :)
